name: rastreiodex
description: "Aplicativo de Rastreio de encomendas Sedex"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  cloud_firestore: ^6.1.1
  firebase_messaging: ^16.1.0
  firebase_core: ^4.3.0
  intl: ^0.20.2
  adaptive_theme: ^3.6.0
  flutter_local_notifications: ^19.5.0
  shared_preferences: ^2.2.2
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  
  share_plus: ^10.0.0
  screenshot: ^3.0.0
  path_provider: ^2.1.2
  shimmer: ^3.0.0
  home_widget: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
